### ISSUE TITLE
I want to know how to set subdirectory

### ISSUE THREAD

**Issue by HerbertHe** [fraoustin/Nginx-Fancyindex-Theme#9]
when included subdirectory, I click to open show 404, and not the theme page

**Comment by fraoustin** [comment]
Hi thank you for your return
what is the configuration of your nginx?
If you have a 404 error the problem is your configuration of nginx

**Comment by HerbertHe** [comment]
same as `README.md`, subdirectory is not ok

**Comment by HerbertHe** [comment]
my website is [download](https://download.jieec.cn)

**Comment by fraoustin** [comment]
Hi it is ok for me
![image](https://user-images.githubusercontent.com/3457495/79954400-90013c80-847d-11ea-9bde-9a9c52514b24.png)
And i can download Dartup.pdf (but i don't undestand ;-) )

**Comment by HerbertHe** [comment]
but when I click the subdirectory `biaoqingbao`, it is not working

**Comment by fraoustin** [comment]
Hi

can you test with image docker fraoustin/fancyindex (https://github.com/fraoustin/fancyindex)

I thank that the problem from nginx conf

**Comment by HerbertHe** [comment]
I know the trouble, I need to copy the theme into the directroy where I want to use, and I have solved it by copying the theme
